---

- name: ensure devices mounted
  mount:
    name: '{{ item.name }}'
    src: '{{ item.src }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.opts  | default("defaults") }}'
    state: '{{ item.state  | default("mounted")  }}'
    dump: '{{ item.dump | default("0") }}'
    passno: '{{ item.passno | default("0") }}'
    fstab: '{{ item.fstab | default("/etc/fstab") }}'
  with_items: mount_devices